name: run

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: 0 1 * * *

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - run: npm ci
      
      - name: Debug secrets
        run: |
          echo "GLADOS set? ${GLADOS:+yes}"
          echo "NOTIFY set? ${NOTIFY:+yes}"
        env:
          GLADOS: ${{ secrets.GLADOS }}
          NOTIFY: ${{ secrets.NOTIFY }}
          
      - run: npm run main
        env:
          GLADOS: ${{ secrets.GLADOS }}
          NOTIFY: ${{ secrets.NOTIFY }}
      - run: echo "Finished main script."
